### ISSUE TITLE
Add multi user support for remote systems

### ISSUE THREAD

**Issue by jogrie** [agoloncser/ansible-role-shell-fish#2]
there should be the possibility to install fish on remote servers for multiple users

**Comment by agl4** [comment]
@jogrie Actually I was able to run the unmodified code on a remote system, it is just the matter of inventory.

```
❯ cat fish-remote.yml 
---
- name: shell_fish
  hosts: all
  remote_user: root
  roles:
    - agoloncser.shell_fish

❯ cat inventory/bsd/hosts.yml 
---
all: 
  hosts:
    host0.network.local: {}
```

The remote user can be set with the `remote_user` key in the play.
